### ISSUE TITLE
Redesign UI using bootstrap 5

### ISSUE THREAD

**Issue by zjsbaltazar-tip** [zjsbaltazar-tip/grp9-iptracker#2]
The design of the UI must be responsive and dynamic to any size. I would recommend using the bootstrap framework because it has a lot of features that are easy to implement.

**Comment by crebello26** [comment]
I'll try to do the issue

**Comment by crebello26** [comment]
I redesigned the UI using bootstrap, and the commit is https://github.com/zjsbaltazar-tip/grp9-iptracker/commit/b609797e1e396fe96c88dd2317860fff89baff44

**Comment by zjsbaltazar-tip** [comment]
The issue has been resolved.
