### ISSUE TITLE
Update UI and change the theme

### ISSUE THREAD

**Issue by zjsbaltazar-tip** [zjsbaltazar-tip/grp9-iptracker#3]
To make the page more appealing, we need to add a small decoration.

**Comment by jaras001** [comment]
Ok I'll decorate the page and I will make it more interesting

**Comment by jaras001** [comment]
I finish decorating the pages and this is the commit https://github.com/zjsbaltazar-tip/grp9-iptracker/commit/4e799c54a939540bda4a3a97c1ca7dbd5239b0a2

**Comment by zjsbaltazar-tip** [comment]
The issue has been resolved.
